### ISSUE TITLE
 (1/1) Error Call to a member function toArray() on null

### ISSUE THREAD

**Issue by parthajudiyap** [Brille24/SyliusCustomOptionsPlugin#32] opened 2019-05-01 10:55 UTC
in OrderItemCustomerOptionCapableTrait.php line 50
--
at OrderItem->getCustomerOptionConfiguration()in CoreExtension.php line 1681

https://ibb.co/SKh4L8V

**Comment by mamazu** [comment] 2019-05-06 15:28
Duplicate of #35

**Closed by mamazu** 2019-05-06 15:28 UTC
